# Generated by Django 5.2 on 2025-09-23 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category_remove_product_image_product_description_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together=set(),
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100)),
                (
                    "attribute_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="shop.attributetype",
                    ),
                ),
            ],
            options={
                "unique_together": {("attribute_type", "value")},
            },
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="shop.attributevalue",
            ),
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="attribute_type",
        ),
    ]
