# Generated by Django 5.2 on 2025-09-24 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_productattribute_unique_together_and_more"),
    ]

    operations = []
