# Generated by Django 5.2 on 2025-10-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_create_attributevalue_fix"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="productimage",
            name="unique_primary_image_per_product",
        ),
        migrations.AlterUniqueTogether(
            name="attributetype",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="attributevalue",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="productattribute",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="attributetype",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="attributevalue",
            name="value",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="value",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.attributevalue"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.RemoveField(
            model_name="attributetype",
            name="category",
        ),
    ]
