# Generated by Django 5.2 on 2025-10-03 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattribute",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_attributes",
                to="shop.product",
            ),
        ),
    ]
