# Generated by Django 5.2 on 2025-10-03 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_productattribute_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="external_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
