# Generated by Django 5.2 on 2025-10-04 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_product_external_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productattribute",
            unique_together={("product", "value")},
        ),
    ]
