# Generated by Django 5.2 on 2025-10-05 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_alter_productattribute_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductVariation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                (
                    "attributes",
                    models.ManyToManyField(
                        related_name="product_variations", to="shop.attributevalue"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variations",
                        to="shop.product",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
    ]
