# Generated by Django 5.2 on 2025-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_productvariation_delete_productattribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="delivery_time",
            field=models.CharField(
                default="In 1-2 Werktagen bei dir!",
                help_text="Lieferzeit für dieses Produkt",
                max_length=100,
            ),
        ),
    ]
