# Generated by Django 5.2 on 2025-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_product_rating_avg_product_rating_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="paypal", max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="zip",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
