# Generated by Django 5.2 on 2025-10-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_order_city_order_name_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_image",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
