# Generated by Django 5.2 on 2025-11-05 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_alter_orderitem_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="rating_avg",
        ),
        migrations.RemoveField(
            model_name="product",
            name="rating_count",
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="delivery_time",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="shop.deliverytime",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="external_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="productvariation",
            name="attributes",
            field=models.ManyToManyField(
                related_name="variations", to="shop.attributevalue"
            ),
        ),
    ]
