# Generated by Django 5.2 on 2025-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0016_alter_product_main_image_alter_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating_avg",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
