# Generated by Django 5.2 on 2025-11-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_review_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("ready_to_ship", "Versandbereit"),
                    ("shipped", "Versandt"),
                    ("cancelled", "Storniert"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
