# Generated by Django 5.2 on 2025-11-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dhl", "DHL"),
                    ("hermes", "Hermes"),
                    ("ups", "UPS"),
                    ("post", "Deutsche Post"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
