# Generated by Django 5.2 on 2025-12-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0021_orderreturn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderreturn",
            name="processed",
        ),
        migrations.AddField(
            model_name="orderreturn",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Offen"),
                    ("approved", "Genehmigt"),
                    ("rejected", "Abgelehnt"),
                    ("received", "Eingetroffen"),
                    ("refunded", "Erstattet"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
