# Generated by Django 5.2 on 2026-01-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0027_add_refund_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="external_image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
