"""
Django settings for mybackend project.

Generated by 'django-admin startproject' using Django 5.2.
"""

from pathlib import Path

# BASE_DIR = root/backend
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------------------------------------------------
# SECURITY
# -------------------------------------------------------------------
SECRET_KEY = "django-insecure-&_arp@e0_c(h@dsu4+yevi54k=d&d_2svt)kro)$l7jjk-+pu!"
DEBUG = True
ALLOWED_HOSTS: list[str] = []

# -------------------------------------------------------------------
# Application definition
# -------------------------------------------------------------------
INSTALLED_APPS = [
    # Django built-ins
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",     # <-- Sessions aktivieren
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Dritt-Anbieter
    "rest_framework",
    "corsheaders",                 # <-- CORS

    # Eigene Apps
    "shop",
]

MIDDLEWARE = [
    # CORS muss ganz oben stehen
    "corsheaders.middleware.CorsMiddleware",

    # Django-Middleware
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mybackend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],  # eigene Template-Ordner
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mybackend.wsgi.application"

# -------------------------------------------------------------------
# Database
# -------------------------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -------------------------------------------------------------------
# Password validation
# -------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -------------------------------------------------------------------
# Internationalization
# -------------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# -------------------------------------------------------------------
# Static files
# -------------------------------------------------------------------
STATIC_URL = "static/"

# -------------------------------------------------------------------
# Default primary key field type
# -------------------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -------------------------------------------------------------------
# CORS settings
# -------------------------------------------------------------------
# Erlaubt das Setzen und Mitgeben von Session-Cookies
CORS_ALLOW_CREDENTIALS = True

# Hosts, die CORS-zugriff haben
CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",     # Angular Dev Server
    # später z.B. "https://your-production-domain.com"
]

# Optional: wenn du alle Origins (nur für Entwicklung!) erlauben willst:
# CORS_ALLOW_ALL_ORIGINS = True

# -------------------------------------------------------------------
# REST Framework (optional Erweiterungen)
# -------------------------------------------------------------------
REST_FRAMEWORK = {
    # z.B. Standard-Permission
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ]
}


# Session-Cookie auch in Dev als Secure markieren,
# damit SameSite=None funktioniert
SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

# Gleiches für CSRF-Cookie, falls du CSRF nutzt:
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True
